// package handling the creation and comparing of tokens.
//
// note: a token is a str used for authentication, generated
// at random.
package token

// token generated by a generator.
type token struct {
	Str        string `json:"repr"`
	Creation   int64  `json:"creation_time"`
	Expiration int64  `json:"expires_in,omitempty"`
}

func (t *token) Expires() bool {
	return t.Expiration > 0
}

// normally we could just use the string and compare it
// without using this function. But as we suggest using this method
// as it is more clear what happens, we create it here :)
func (t *token) Is(token0 string) bool {
	return t.Str == token0
}
